version: '3.8'

services:
  gateway:
    image: hmunoz79/apigateway:1.5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9600:9500"
    environment:
      SPRING_SERVER_PORT: 9500
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://peliculas-app:8080
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: pelicula-service
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/api/**
    depends_on:
      - peliculas-app

  peliculas-app:
    build: .
    container_name: peliculas-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://peliculas-db:5432/peliculas_db
      SPRING_DATASOURCE_USERNAME: user_peliculas
      SPRING_DATASOURCE_PASSWORD: pass_peliculas

      # Configuración RabbitMQ
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

      # Nombre del exchange que se usará
      APP_RABBITMQ_EXCHANGE: peliculas.exchange
    depends_on:
      - peliculas-db
      - rabbitmq

  peliculas-db:
    image: postgres:13-alpine
    container_name: peliculas-db-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: peliculas_db
      POSTGRES_USER: user_peliculas
      POSTGRES_PASSWORD: pass_peliculas
    volumes:
      - peliculas-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"   # puerto de conexión
      - "15672:15672" # interfaz web de RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  peliculas-data:
  rabbitmq_data:
