# ===============================
# Configuracion de aplicacion
# ===============================
server.port=8080
spring.application.name=pelicula-service

# ===============================
# Configuracion de Base de Datos
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/peliculas_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_peliculas}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pass_peliculas}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always

# ===============================
# RabbitMQ
# ===============================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ Exchange (debe coincidir con carrito)
app.rabbitmq.exchange=${APP_RABBITMQ_EXCHANGE:pelicula_exchange}
# RabbitMQ Routing Key (debe coincidir con carrito)
app.rabbitmq.routing.key=${APP_RABBITMQ_ROUTING_KEY:pelicula.event}

# ===============================
# Keycloak
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/cinecloud

# ===============================
# Inicialización de datos
# ===============================
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

# ===============================
# Historial Compras
# ===============================
historial.base-url=${HISTORIAL_BASE_URL:http://localhost:8083}