#name: cloudpelicula
#services:
 # gateway:
  #  image: hmunoz79/apigateway:1.5
  #  extra_hosts:
  #    - "host.docker.internal:host-gateway"
  #  ports:
  #    - "9600:9600"
  #  environment:
  #    SPRING_SERVER_PORT: 9600
  #    SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://peliculas-app:8080
  #    SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: pelicula-service
  #    SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/api/**

